# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Production Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    types:
    - closed
    branches: [ "main" ]

jobs:

  build:
    if: github.event.pull_request.merged == true || github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Deploying
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        port: ${{ secrets.PORT }}
        key: ${{ secrets.SSHKEY }}
        script: |
          cd /var/www/wc-admin-dev
          sudo git checkout main
          sudo git pull origin main
          sudo npm ci --force
          sudo npm run generate
          #sudo rm -rf node_modules

